<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Jay-PC" ignored="0" name="HRMTest" tests="7" failures="3" timestamp="18 Nov 2019 04:00:12 GMT" time="104.83" errors="0">
  <testcase name="TC_001_Login_Test" time="6.608" classname="com.HRM.TestCases.TC_Login_Test_001"/>
  <testcase name="TC_002_Login_DDT" time="9.216" classname="com.HRM.TestCases.TC_Login_DDT_002"/>
  <testcase name="TC_002_Login_DDT" time="3.805" classname="com.HRM.TestCases.TC_Login_DDT_002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.HRM.TestCases.TC_Login_DDT_002.TC_002_Login_DDT(TC_Login_DDT_002.java:66)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- TC_002_Login_DDT -->
  <testcase name="TC_002_Login_DDT" time="6.628" classname="com.HRM.TestCases.TC_Login_DDT_002"/>
  <testcase name="TC_002_Login_DDT" time="5.265" classname="com.HRM.TestCases.TC_Login_DDT_002"/>
  <testcase name="TC_002_Login_DDT" time="3.326" classname="com.HRM.TestCases.TC_Login_DDT_002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.HRM.TestCases.TC_Login_DDT_002.TC_002_Login_DDT(TC_Login_DDT_002.java:66)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- TC_002_Login_DDT -->
  <testcase name="TC_003_AddNewEmployee" time="11.971" classname="com.HRM.TestCases.TC_Add_Employee_003">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.HRM.TestCases.TC_Add_Employee_003.TC_003_AddNewEmployee(TC_Add_Employee_003.java:37)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- TC_003_AddNewEmployee -->
</testsuite> <!-- HRMTest -->
